version: '3.8'

services:
  # SQL Server
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ecommerce-sql-server
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings__conStr=Server=sql-server;Database=Ecommerce;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=true;
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - ecommerce-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrongPassword123!" -Q "SELECT 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Backend API
  backend:
    build:
      context: ./backend/loginPage
      dockerfile: Dockerfile
    ports:
      - "5163:80"
      - "5443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80    # ——> يخلي Kestrel يستمع على كل الواجهات
      - ConnectionStrings__conStr=Server=sql-server;Database=Ecommerce;User Id=sa;Password=pass@word;TrustServerCertificate=true;
      - JWt__Issuer=http://localhost:5163
      - JWt__Audience=http://localhost:8080
    depends_on:
      - sql-server
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  sql-data:
    name: ecommerce-db-data